//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface AdCompCheckTool : NSObject
{
    NSArray *matchLanding;
}

+ (id)sharedTool;
@property(retain, nonatomic) NSArray *matchLanding; // @synthesize matchLanding;
- (void).cxx_destruct;
- (id)getPixelColorAtLocation:(struct CGPoint)arg1 withImage:(char *)arg2 andImageWidth:(unsigned long long)arg3;
- (_Bool)isEmptyAd:(id)arg1;
- (_Bool)isLandingUrl:(id)arg1;
- (void)dealloc;
- (id)init;

@end

