//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Function Pointers and Blocks

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct Acceleration {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    unsigned int _field3;
    int _field4;
    void *_field5;
    double _field6;
    double _field7;
    double _field8;
    double _field9;
};

struct ActionManager;

struct AdSize {
    int _field1;
    int _field2;
};

struct CGAffineTransform {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
};

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct CGVector {
    double dx;
    double dy;
};

struct CLLocationCoordinate2D {
    double latitude;
    double longitude;
};

struct Color3B {
    unsigned char _field1;
    unsigned char _field2;
    unsigned char _field3;
};

struct ComponentContainer;

struct Director;

struct EventDispatcher;

struct EventListenerTouchOneByOne;

struct GADAdSize {
    struct CGSize size;
    unsigned long long flags;
};

struct GLProgramState;

struct JKConstBuffer {
    struct JKConstPtrRange _field1;
};

struct JKConstPtrRange {
    char *_field1;
    unsigned long long _field2;
};

struct JKEncodeCache {
    id _field1;
    unsigned long long _field2;
    unsigned long long _field3;
};

struct JKEncodeState {
    struct JKManagedBuffer _field1;
    struct JKManagedBuffer _field2;
    unsigned long long _field3;
    struct JKFastClassLookup _field4;
    struct JKEncodeCache _field5[1024];
    unsigned long long _field6;
    unsigned long long _field7;
    unsigned long long _field8;
    id _field9;
    id _field10;
    SEL _field11;
    CDUnknownFunctionPointerType _field12;
    CDUnknownBlockType _field13;
};

struct JKFastClassLookup {
    void *_field1;
    void *_field2;
    void *_field3;
    void *_field4;
    void *_field5;
};

struct JKHashTableEntry {
    unsigned long long _field1;
    id _field2;
    id _field3;
};

struct JKManagedBuffer {
    struct JKPtrRange _field1;
    unsigned long long _field2;
    unsigned long long _field3;
};

struct JKObjCImpCache {
    Class _field1;
    CDUnknownFunctionPointerType _field2;
    CDUnknownFunctionPointerType _field3;
};

struct JKObjectStack {
    void **_field1;
    void **_field2;
    unsigned long long *_field3;
    unsigned long long _field4;
    unsigned long long _field5;
    unsigned long long _field6;
    unsigned long long _field7;
};

struct JKParseState {
    unsigned long long _field1;
    struct JKConstBuffer _field2;
    unsigned long long _field3;
    unsigned long long _field4;
    unsigned long long _field5;
    unsigned long long _field6;
    unsigned long long _field7;
    unsigned long long _field8;
    struct JKParseToken _field9;
    struct JKObjectStack _field10;
    struct JKTokenCache _field11;
    struct JKObjCImpCache _field12;
    id _field13;
    int _field14;
    _Bool _field15;
};

struct JKParseToken {
    struct JKConstPtrRange _field1;
    unsigned long long _field2;
    struct JKTokenValue _field3;
    struct JKManagedBuffer _field4;
};

struct JKPtrRange {
    char *_field1;
    unsigned long long _field2;
};

struct JKTokenCache {
    struct JKTokenCacheItem *_field1;
    unsigned long long _field2;
    unsigned int _field3;
    unsigned char _field4[1024];
};

struct JKTokenCacheItem;

struct JKTokenValue {
    struct JKConstPtrRange _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    union {
        long long _field1;
        unsigned long long _field2;
        double _field3;
    } _field4;
    struct JKTokenCacheItem *_field5;
};

struct Map<int, cocos2d::ui::LayoutParameter *> {
    struct unordered_map<int, cocos2d::ui::LayoutParameter *, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<const int, cocos2d::ui::LayoutParameter *>>> _field1;
};

struct Mat4 {
    float _field1[16];
};

struct NSMutableArray {
    Class _field1;
};

struct Node;

struct PLCrashHostInfoVersion {
    unsigned long long major;
    unsigned long long minor;
    unsigned long long revision;
};

struct PLCrashReporterCallbacks {
    unsigned short _field1;
    void *_field2;
    CDUnknownFunctionPointerType _field3;
};

struct PhysicsBody;

struct Quaternion {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
};

struct Ref;

struct Scheduler;

struct Size {
    float _field1;
    float _field2;
};

struct UIEdgeInsets {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
};

struct Vec2 {
    float _field1;
    float _field2;
};

struct Vector<cocos2d::Node *> {
    struct vector<cocos2d::Node *, std::__1::allocator<cocos2d::Node *>> _field1;
};

struct VideoPlayer {
    CDUnknownFunctionPointerType *_field1;
    unsigned int _field2;
    unsigned int _field3;
    int _field4;
    void *_field5;
    float _field6;
    float _field7;
    float _field8;
    float _field9;
    struct Quaternion _field10;
    float _field11;
    float _field12;
    float _field13;
    struct Vec2 _field14;
    float _field15;
    struct Vec2 _field16;
    _Bool _field17;
    _Bool _field18;
    float _field19;
    float _field20;
    struct Vec2 _field21;
    struct Vec2 _field22;
    struct Size _field23;
    _Bool _field24;
    struct Mat4 _field25;
    struct Mat4 _field26;
    _Bool _field27;
    struct Mat4 _field28;
    _Bool _field29;
    struct Mat4 _field30;
    _Bool _field31;
    _Bool _field32;
    int _field33;
    float _field34;
    struct Vector<cocos2d::Node *> _field35;
    struct Node *_field36;
    struct Director *_field37;
    int _field38;
    basic_string_7c0a1c0b _field39;
    unsigned long long _field40;
    void *_field41;
    struct Ref *_field42;
    struct GLProgramState *_field43;
    int _field44;
    struct Scheduler *_field45;
    struct ActionManager *_field46;
    struct EventDispatcher *_field47;
    _Bool _field48;
    _Bool _field49;
    _Bool _field50;
    _Bool _field51;
    _Bool _field52;
    int _field53;
    int _field54;
    int _field55;
    struct ComponentContainer *_field56;
    struct PhysicsBody *_field57;
    float _field58;
    float _field59;
    float _field60;
    _Bool _field61;
    _Bool _field62;
    unsigned char _field63;
    unsigned char _field64;
    struct Color3B _field65;
    struct Color3B _field66;
    _Bool _field67;
    _Bool _field68;
    unsigned short _field69;
    struct function<void ()> _field70;
    struct function<void ()> _field71;
    struct function<void ()> _field72;
    struct function<void ()> _field73;
    struct Vector<cocos2d::Node *> _field74;
    _Bool _field75;
    CDUnknownFunctionPointerType *_field76;
    struct function<void (cocos2d::ui::Widget *, cocos2d::ui::Widget *)> _field77;
    struct function<cocos2d::ui::Widget *(cocos2d::ui::Widget::FocusDirection)> _field78;
    _Bool _field79;
    _Bool _field80;
    _Bool _field81;
    _Bool _field82;
    _Bool _field83;
    _Bool _field84;
    _Bool _field85;
    _Bool _field86;
    _Bool _field87;
    int _field88;
    int _field89;
    int _field90;
    int _field91;
    struct Size _field92;
    struct Vec2 _field93;
    struct Vec2 _field94;
    _Bool _field95;
    struct EventListenerTouchOneByOne *_field96;
    struct Vec2 _field97;
    struct Vec2 _field98;
    struct Vec2 _field99;
    _Bool _field100;
    _Bool _field101;
    struct Map<int, cocos2d::ui::LayoutParameter *> _field102;
    int _field103;
    _Bool _field104;
    _Bool _field105;
    struct Ref *_field106;
    struct function<void (cocos2d::Ref *, cocos2d::ui::Widget::TouchEventType)> _field107;
    struct function<void (cocos2d::Ref *)> _field108;
    struct function<void (cocos2d::Ref *, int)> _field109;
    basic_string_7c0a1c0b _field110;
    basic_string_7c0a1c0b _field111;
    _Bool _field112;
    _Bool _field113;
    _Bool _field114;
    _Bool _field115;
    basic_string_7c0a1c0b _field116;
    int _field117;
    int _field118;
    struct function<void (cocos2d::Ref *, cocos2d::experimental::ui::VideoPlayer::EventType)> _field119;
    void *_field120;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct _PLCrashReportDecoder {
    struct _Plcrash__CrashReport *_field1;
};

struct _Plcrash__CrashReport {
    struct _ProtobufCMessage _field1;
    struct _Plcrash__CrashReport__SystemInfo *_field2;
    struct _Plcrash__CrashReport__ApplicationInfo *_field3;
    unsigned long long _field4;
    struct _Plcrash__CrashReport__Thread **_field5;
    unsigned long long _field6;
    struct _Plcrash__CrashReport__BinaryImage **_field7;
    struct _Plcrash__CrashReport__Exception *_field8;
    struct _Plcrash__CrashReport__Signal *_field9;
    struct _Plcrash__CrashReport__ProcessInfo *_field10;
    struct _Plcrash__CrashReport__MachineInfo *_field11;
    struct _Plcrash__CrashReport__ReportInfo *_field12;
};

struct _Plcrash__CrashReport__ApplicationInfo {
    struct _ProtobufCMessage _field1;
    char *_field2;
    char *_field3;
    char *_field4;
};

struct _Plcrash__CrashReport__BinaryImage;

struct _Plcrash__CrashReport__Exception {
    struct _ProtobufCMessage _field1;
    char *_field2;
    char *_field3;
    unsigned long long _field4;
    struct _Plcrash__CrashReport__Thread__StackFrame **_field5;
};

struct _Plcrash__CrashReport__MachineInfo {
    struct _ProtobufCMessage _field1;
    char *_field2;
    struct _Plcrash__CrashReport__Processor *_field3;
    unsigned int _field4;
    unsigned int _field5;
};

struct _Plcrash__CrashReport__ProcessInfo {
    struct _ProtobufCMessage _field1;
    char *_field2;
    unsigned int _field3;
    char *_field4;
    char *_field5;
    unsigned int _field6;
    int _field7;
    int _field8;
    unsigned long long _field9;
};

struct _Plcrash__CrashReport__Processor {
    struct _ProtobufCMessage _field1;
    int _field2;
    int _field3;
    unsigned long long _field4;
    unsigned long long _field5;
};

struct _Plcrash__CrashReport__ReportInfo;

struct _Plcrash__CrashReport__Signal {
    struct _ProtobufCMessage _field1;
    char *_field2;
    char *_field3;
    unsigned long long _field4;
    struct _Plcrash__CrashReport__Signal__MachException *_field5;
};

struct _Plcrash__CrashReport__Signal__MachException {
    struct _ProtobufCMessage _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    unsigned long long *_field4;
};

struct _Plcrash__CrashReport__Symbol {
    struct _ProtobufCMessage _field1;
    char *_field2;
    unsigned long long _field3;
    int _field4;
    unsigned long long _field5;
};

struct _Plcrash__CrashReport__SystemInfo {
    struct _ProtobufCMessage _field1;
    int _field2;
    int _field3;
    char *_field4;
    int _field5;
    long long _field6;
    char *_field7;
};

struct _Plcrash__CrashReport__Thread;

struct _Plcrash__CrashReport__Thread__StackFrame {
    struct _ProtobufCMessage _field1;
    unsigned long long _field2;
    struct _Plcrash__CrashReport__Symbol *_field3;
};

struct _ProtobufCMessage {
    struct _ProtobufCMessageDescriptor *_field1;
    unsigned int _field2;
    struct _ProtobufCMessageUnknownField *_field3;
};

struct _ProtobufCMessageDescriptor;

struct _ProtobufCMessageUnknownField;

struct __darwin_sigaltstack {
    void *ss_sp;
    unsigned long long ss_size;
    int ss_flags;
};

struct __hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*> {
    struct __hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*> *_field1;
};

struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> {
    struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> {
        struct __rep {
            union {
                struct __long {
                    char *_field1;
                    unsigned long long _field2;
                    unsigned long long _field3;
                } _field1;
                struct __short {
                    char _field1[23];
                    struct {
                        unsigned char _field1;
                    } _field2;
                } _field2;
                struct __raw {
                    unsigned long long _field1[3];
                } _field3;
            } _field1;
        } _field1;
    } _field1;
};

struct function<bool (std::__1::basic_string<char>)> {
    struct type __buf_;
    struct __base<bool (std::__1::basic_string<char>)> *__f_;
};

struct function<cocos2d::ui::Widget *(cocos2d::ui::Widget::FocusDirection)> {
    struct type _field1;
    struct __base<cocos2d::ui::Widget *(cocos2d::ui::Widget::FocusDirection)> *_field2;
};

struct function<void ()> {
    struct type _field1;
    struct __base<void ()> *_field2;
};

struct function<void (cocos2d::Ref *)> {
    struct type _field1;
    struct __base<void (cocos2d::Ref *)> *_field2;
};

struct function<void (cocos2d::Ref *, cocos2d::experimental::ui::VideoPlayer::EventType)> {
    struct type _field1;
    struct __base<void (cocos2d::Ref *, cocos2d::experimental::ui::VideoPlayer::EventType)> *_field2;
};

struct function<void (cocos2d::Ref *, cocos2d::ui::Widget::TouchEventType)> {
    struct type _field1;
    struct __base<void (cocos2d::Ref *, cocos2d::ui::Widget::TouchEventType)> *_field2;
};

struct function<void (cocos2d::Ref *, int)> {
    struct type _field1;
    struct __base<void (cocos2d::Ref *, int)> *_field2;
};

struct function<void (cocos2d::ui::Widget *, cocos2d::ui::Widget *)> {
    struct type _field1;
    struct __base<void (cocos2d::ui::Widget *, cocos2d::ui::Widget *)> *_field2;
};

struct function<void (std::__1::basic_string<char>)> {
    struct type __buf_;
    struct __base<void (std::__1::basic_string<char>)> *__f_;
};

struct in6_addr {
    union {
        unsigned char _field1[16];
        unsigned short _field2[8];
        unsigned int _field3[4];
    } _field1;
};

struct in_addr {
    unsigned int _field1;
};

struct plcrash_exception_server_context {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    CDUnknownFunctionPointerType _field5;
    void *_field6;
    struct _opaque_pthread_mutex_t {
        long long _field1;
        char _field2[56];
    } _field7;
    struct _opaque_pthread_cond_t {
        long long _field1;
        char _field2[40];
    } _field8;
    unsigned int _field9;
    _Bool _field10;
};

struct plcrash_mach_exception_port_set {
    unsigned int count;
    unsigned int masks[14];
    unsigned int ports[14];
    int behaviors[14];
    int flavors[14];
};

struct sockaddr {
    unsigned char _field1;
    unsigned char _field2;
    char _field3[14];
};

struct sockaddr_in {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    struct in_addr _field4;
    char _field5[8];
};

struct sockaddr_in6 {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    unsigned int _field4;
    struct in6_addr _field5;
    unsigned int _field6;
};

struct sockaddr_un {
    unsigned char _field1;
    unsigned char _field2;
    char _field3[104];
};

struct tagSZRequestItem {
    char *_field1;
    char *_field2;
    int _field3;
};

struct timeval {
    long long tv_sec;
    int tv_usec;
};

struct type {
    unsigned char __lx[24];
};

struct unique_ptr<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>*[], std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>*>>> {
    struct __compressed_pair<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>**, std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>*>>> {
        struct __hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*> **_field1;
        struct __bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>*>> {
            struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>*>> {
                unsigned long long _field1;
            } _field1;
        } _field2;
    } _field1;
};

struct unordered_map<int, cocos2d::ui::LayoutParameter *, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<const int, cocos2d::ui::LayoutParameter *>>> {
    struct __hash_table<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, std::__1::__unordered_map_hasher<int, std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, std::__1::hash<int>, true>, std::__1::__unordered_map_equal<int, std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, std::__1::equal_to<int>, true>, std::__1::allocator<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>>> {
        struct unique_ptr<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>*[], std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>*>>> _field1;
        struct __compressed_pair<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*>, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>>> {
            struct __hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, void *>*> _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__unordered_map_hasher<int, std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, std::__1::hash<int>, true>> {
            unsigned long long _field1;
        } _field3;
        struct __compressed_pair<float, std::__1::__unordered_map_equal<int, std::__1::__hash_value_type<int, cocos2d::ui::LayoutParameter *>, std::__1::equal_to<int>, true>> {
            float _field1;
        } _field4;
    } _field1;
};

struct vector<cocos2d::Node *, std::__1::allocator<cocos2d::Node *>> {
    struct Node **_field1;
    struct Node **_field2;
    struct __compressed_pair<cocos2d::Node **, std::__1::allocator<cocos2d::Node *>> {
        struct Node **_field1;
    } _field3;
};

struct vector<unsigned char, std::__1::allocator<unsigned char>> {
    char *_field1;
    char *_field2;
    struct __compressed_pair<unsigned char *, std::__1::allocator<unsigned char>> {
        char *_field1;
    } _field3;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned long long _field1;
    id *_field2;
    unsigned long long *_field3;
    unsigned long long _field4[5];
} CDStruct_70511ce9;

typedef struct {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
    double _field5;
    double _field6;
    double _field7;
    double _field8;
    double _field9;
} CDStruct_27b5ccfc;

typedef struct {
    long long version;
    void *info;
    CDUnknownFunctionPointerType retain;
    CDUnknownFunctionPointerType release;
    CDUnknownFunctionPointerType copyDescription;
} CDStruct_4210025a;

typedef struct {
    long long value;
    int timescale;
    unsigned int flags;
    long long epoch;
} CDStruct_1b6d18a9;

typedef struct {
    long long majorVersion;
    long long minorVersion;
    long long patchVersion;
} CDStruct_f6aba300;

// Template types
typedef struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> {
    struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> {
        struct __rep {
            union {
                struct __long {
                    char *_field1;
                    unsigned long long _field2;
                    unsigned long long _field3;
                } _field1;
                struct __short {
                    char _field1[23];
                    struct {
                        unsigned char _field1;
                    } _field2;
                } _field2;
                struct __raw {
                    unsigned long long _field1[3];
                } _field3;
            } _field1;
        } _field1;
    } _field1;
} basic_string_7c0a1c0b;

typedef struct function<bool (std::__1::basic_string<char>)> {
    struct type __buf_;
    struct __base<bool (std::__1::basic_string<char>)> *__f_;
} function_10b5811e;

typedef struct function<void (std::__1::basic_string<char>)> {
    struct type __buf_;
    struct __base<void (std::__1::basic_string<char>)> *__f_;
} function_ef19a04c;

typedef struct vector<unsigned char, std::__1::allocator<unsigned char>> {
    char *_field1;
    char *_field2;
    struct __compressed_pair<unsigned char *, std::__1::allocator<unsigned char>> {
        char *_field1;
    } _field3;
} vector_5b3bfa18;

#pragma mark Named Unions

union _GLKMatrix4 {
    struct {
        float m00;
        float m01;
        float m02;
        float m03;
        float m10;
        float m11;
        float m12;
        float m13;
        float m20;
        float m21;
        float m22;
        float m23;
        float m30;
        float m31;
        float m32;
        float m33;
    } ;
    float m[16];
};

