//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SKPaymentTransactionObserver-Protocol.h"
#import "SKProductsRequestDelegate-Protocol.h"

@class NSString;

@interface IAP : NSObject <SKProductsRequestDelegate, SKPaymentTransactionObserver>
{
    void *mShop;
}

+ (id)sharedInstance;
- (void)dealloc;
- (void)verifyPurchaseWithPaymentTransaction;
- (void)save;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)paymentQueue:(id)arg1 restoreCompletedTransactionsFailedWithError:(id)arg2;
- (void)restoreTransaction:(id)arg1;
- (void)paymentQueueRestoreCompletedTransactionsFinished:(id)arg1;
- (void)failedTransaction:(id)arg1;
- (void)provideContent:(id)arg1;
- (void)recordTransaction:(id)arg1;
- (void)completeTransaction:(id)arg1;
- (void)removeWaiting;
- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (void)PurchasedTransaction:(id)arg1;
- (void)requestDidFinish:(id)arg1;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)requestProUpgradeProductData;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)RequestProductData;
- (_Bool)CanMakePay;
- (void)setShop:(void *)arg1;
- (void)buy;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

