//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "GKAchievementViewControllerDelegate-Protocol.h"
#import "GKLeaderboardViewControllerDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class NSString;

@interface ShowAchievements : UIViewController <GKLeaderboardViewControllerDelegate, GKAchievementViewControllerDelegate, UIAlertViewDelegate>
{
    _Bool mIsErrorView;
    UIViewController *tempVC;
}

+ (id)sharedShowAchievements;
@property(retain, nonatomic) UIViewController *tempVC; // @synthesize tempVC;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)leaderboardViewControllerDidFinish:(id)arg1;
- (void)showLeaderboard;
- (void)achievementViewControllerDidFinish:(id)arg1;
- (void)showAchievements;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)loadErrorView;
- (void)showDownGame;
- (void)showDirectEnterGame;
- (void)showShop;
- (void)showRemoveAdTip;
- (void)show2048Ad;
- (void)loadAlertView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

