//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL, UIImage;

@interface SIPhoto : NSObject
{
    UIImage *_image;
    NSURL *_objectURL;
    unsigned long long _rating;
    NSString *_title;
}

+ (id)photoWithObjectURL:(id)arg1 title:(id)arg2 rating:(unsigned long long)arg3 image:(id)arg4;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) unsigned long long rating; // @synthesize rating=_rating;
@property(retain, nonatomic) NSURL *objectURL; // @synthesize objectURL=_objectURL;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;

@end

