//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AddCardToWXCardPackageResp, GetMessageFromWXReq, LaunchFromWXReq, SendAuthResp, SendMessageToWXResp, ShowMessageFromWXReq, WXChooseCardResp, WXChooseInvoiceResp;

@protocol WXApiManagerDelegate <NSObject>

@optional
- (void)managerDidRecvChooseInvoiceResponse:(WXChooseInvoiceResp *)arg1;
- (void)managerDidRecvChooseCardResponse:(WXChooseCardResp *)arg1;
- (void)managerDidRecvAddCardResponse:(AddCardToWXCardPackageResp *)arg1;
- (void)managerDidRecvAuthResponse:(SendAuthResp *)arg1;
- (void)managerDidRecvMessageResponse:(SendMessageToWXResp *)arg1;
- (void)managerDidRecvLaunchFromWXReq:(LaunchFromWXReq *)arg1;
- (void)managerDidRecvShowMessageReq:(ShowMessageFromWXReq *)arg1;
- (void)managerDidRecvGetMessageReq:(GetMessageFromWXReq *)arg1;
@end

